/**
 * nginx-map-builder.ts
 *
 * Pure, dependency-free functions that build an nginx `map` block
 * from landing entries. Extracted for testability — no Prisma or
 * I/O dependencies.
 */

// ── Types ──────────────────────────────────────────────────────────

interface LandingMapEntry {
  readonly id: string;
  readonly slug: string;
  readonly legacyRef: string | null;
  readonly geo: { readonly code: string };
}

// ── Pure functions ─────────────────────────────────────────────────

/**
 * Escape characters that have special meaning in nginx regex context.
 * Does NOT escape `/` since it's a valid literal in nginx regex maps.
 */
const escapeNginxRegex = (raw: string): string =>
  raw.replace(/[.+?^${}()|[\]\\*]/g, "\\$&");

/**
 * Resolve the URI path for a landing entry.
 * Uses `legacyRef` if available, otherwise derives `/<geoCode>/<slug>/`.
 */
const resolvePath = (entry: LandingMapEntry): string =>
  entry.legacyRef ?? `/${entry.geo.code.toLowerCase()}/${entry.slug}/`;

/**
 * Sort entries deterministically by geo code (asc) then slug (asc).
 */
const sortEntries = (entries: readonly LandingMapEntry[]): readonly LandingMapEntry[] =>
  [...entries].sort((a, b) => {
    const geoCompare = a.geo.code.localeCompare(b.geo.code);
    return geoCompare !== 0 ? geoCompare : a.slug.localeCompare(b.slug);
  });

/**
 * Build the full nginx `map` block from a list of landing entries.
 *
 * Output format:
 * ```nginx
 * map $request_uri $ls_landing_id {
 *     default "";
 *     ~^/de/urology/   clxxxxxxxxxx;
 * }
 * ```
 */
const buildNginxMapBlock = (entries: readonly LandingMapEntry[]): string => {
  const sorted = sortEntries(entries);

  const lines: string[] = [
    "# Auto-generated by generate-nginx-map.ts — do not edit manually",
    `# Entries: ${sorted.length}`,
    "",
    "map $request_uri $ls_landing_id {",
    '    default "";'
  ];

  for (const entry of sorted) {
    const path = resolvePath(entry);
    const escaped = escapeNginxRegex(path);
    lines.push(`    ~^${escaped}    ${entry.id};`);
  }

  lines.push("}");
  lines.push("");

  return lines.join("\n");
};

export { buildNginxMapBlock, escapeNginxRegex, resolvePath, sortEntries };
export type { LandingMapEntry };
